#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

admin:
  resource: '../src/Controller/Admin/'
  type: annotation
  prefix: /admin

pub:
  resource: '../src/Controller/Pub/'
  type: annotation
  prefix: /pub

